services:
  - type: web
    name: flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:5000 main:app"
    plan: free
    port: 5000
    envVars:
      - key: FLASK_ENV
        value: production
